### ISSUE TITLE
Static version

### ISSUE THREAD

**Issue by duarteroso** [DerelictOrg/DerelictAL#4]
Hi Michael,

You think a static version of DerelictAL could be added, like glw3 has for instance?
I've already done the changes myself, if it helps.

Cheers,
Duarte

**Comment by mdparker** [comment]
Thanks for mentioning this, Duarte. It was on my TODO list and this motivated me to move it off.

The static binding is now available in version 2.0.0-alpha.2 when specifying either the versions `Derelict_Static` or `DerelictAL_Static`, or the DUB configuration `derelict-al-static`. I can verify that it compiles, but it is as yet untested.

**Comment by duarteroso** [comment]
Cheers mate, as soon as I get it I'll start testing it.
